services:
  - type: web
    name: binance-bot
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    branch: master
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
