services:
  - type: web
    name: binance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
